# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gift Card' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gift Card

  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher'
  pod 'SVProgressHUD'
  pod 'DZNEmptyDataSet'
  pod 'ToastViewSwift'
  
end
